[package]
name = "okra"
version = "0.1.0"
authors = ["Morley, Jonathan <morley.jonathan@gmail.com>"]
edition = "2018"

#[dependencies]
#serde = "1"
#serde_derive = "1"
#serde_str = "0.1"
#kuchiki = "0.7"
#failure = "0.1"
#log = "0.4"
#itertools = "0.8"
#reqwest = "0.9"
#backoff = "0.1"
#dialoguer = "0.3"
#regex = "1"

[dependencies]
serde = "^1.0"
serde_derive = "^1.0"
serde_json = "^1.0"
url = "1.5"
hyper = "~0.11"
serde_yaml = "0.7"
base64 = "~0.7.0"
futures = "0.1.23"

[dev-dependencies]
tokio-core = "*"
